trabalho6/produto/urls.py
from django.urls import path

from produto import views

app_name="produto"
urlpatterns = [
    path('valor-total/', views.valor_total, name='valor-total'),
    path('<int:id>/apagar',views.delete, name='delete'),
    path('index', views.index, name="index"),
    path("new", views.form, name="new"),
    path("edit/<int:id>", views.edita, name="edita"),
    path("lista", views.lista, name="lista")

]

trabalho6/trabalho6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls'))
]

trabalho6/categoria/models.py
from django.db import models
# Create your models here.


class Categoria(models.Model):
    nome  = models.CharField(max_length=50)

    def __str__(self):
        return self.nome
    

trabalho6/produto/models.py
from django.db import models
from categoria.models import Categoria

# Create your models here.
class Produto(models.Model):
    
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    quantidade =  models.IntegerField()
    valor = models.FloatField()
    def valor_final(self):
        return self.valor * self.quantidade

trabalho6/produto/forms.py
from django.forms import ModelForm
from .models import Produto
from django.core.exceptions import ValidationError


class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['categoria','nome', 'quantidade', 'valor']

trabalho6/categoria/views.py
from django.shortcuts import render

# Create your views here.

trabalho6/produto/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .forms import ProdutoForm
from .models import Produto
import json

# Create your views here.

def valor_total(request):
    obj = Produto.objects.all()
    valorTotal = 0
    for i in obj:
        valorTotal += i.valor_final()
    context = {
        "valor_final": valorTotal
    }
    
    return render(request, "produto/valor.html", context)

def lista(request):
    obj = Produto.objects.all()
    
    
    context = {
        "produtos": obj
    }

    return render(request, 'produto/lista.html', context)

def index(request):
    return render(request, 'produto/index.html')


def delete(request,id):
    produto = Produto.objects.get(id=id)
    produto.delete()
    return JsonResponse({"message": "produto removido"})
    
def form(request):
    
    form = ProdutoForm()
    if request.method=="POST":
        print(request.POST)
        form =  ProdutoForm(request.POST)
        if form.is_valid():
            obj = form.save()
            print("Objeto criado com sucesso")
            
            return JsonResponse({"message": "sucesso"  })
        print("Objeto não criado") 
    context = {
        "form": form
    }
    return render(request, 'produto/new.html', context)

def edita(request, id):
    produto = Produto.objects.get(id=id)
    if request.method=="POST":
        print(request.body)
        print((request.body))
        data = json.loads(str(request.body))
        print(data)
       

    return JsonResponse({"message": "erro"})

trabalho6/produto/templates/produto/index.html
{% extends 'base.html' %}

{% block body%}
    <div id="formulario" >

    </div>

    <div id='lista'>
    </div>
{% endblock%}


{% block script %}

    const update_lista = ()=>{
        $.get("{% url  "produto:lista"%}", response => {
            $("#lista").html(response)
        })
    }
    update_lista()
    $.get("{% url  "produto:new"%}", response => {
        
       
        $('#formulario').html(response);
    });


    $("#formulario").submit(function(e){
       
        e.preventDefault();
        const form = $(this).children()[0]
        const obj = $(form).serializeArray()
        
        $.post("{% url  "produto:new"%}", obj, (response) => {
            console.log(response)
            update_lista()
        })
        console.log(obj)

    })

    $("#lista").on("click", ".remove-button", function(){
        const id = $(this).data().id
        const token = $("input[name='csrfmiddlewaretoken']").val()
        console.log(token)
        
        $.post(`${id}/apagar`,{
            "csrfmiddlewaretoken": token
        } , function(){
            update_lista()
        })
    })
{% endblock%}

{% block style%}
    #formulario {
        width: 80%;
        margin: 0 auto;
        margin-top: 40;
    }

     td ,tr{
         text-align: center
    }

    .div-valor-total {
        width: 80%;
        text-align: right;
        font-weight: 800;
    }

{% endblock%}

trabalho6/produto/templates/produto/lista.html
{% load static %}
{% load humanize %}

{% csrf_token %}
<table class="table  table-striped">
    <thead>
        <tr>
        <th scope="col">Categoria</th>
        <th scope="col">Nome</th>
        <th scope="col">Quantidade</th>
        <th scope="col">Preço</th>
        </tr>
  </thead>
    </tbody>
    {% for produto in produtos %} 
        
        <tr>
            <td>
                {{produto.categoria}}
            </td>
            <td>
                {{produto.nome}}
            </td>

            <td>
                <input data-id="{{produto.id}}" class="quantidade-input" value="{{produto.quantidade}}" type="number"/>
            </td>
            
            <td>
                {{produto.valor|floatformat:2|intcomma}}
            </td>
            <td>
                <button class="remove-button" data-id={{produto.id}}> Apagar</button>
            </td>
        
        
        </tr> 

    {% endfor%}
    </tbody>
</table>
<div class="div-valor-total">
    Total: <span id="valor-total">{% block valor_total%} {% endblock %}</span>
</div>
<script>
    const load_valor_total = () => {
        $.get("{% url "produto:valor-total" %}", (response)=>{
            
            $("#valor-total").html(response)
        })
    } 

    $(".quantidade-input").focusout(function(){
        $(this).val()
        const token = $("input[name='csrfmiddlewaretoken']").val()
        const body = {
            "csrfmiddlewaretoken": token,
            'quantidade': $(this).val()
        }
        data =JSON.stringify(body)
        const  id = $(this).data().id
        console.log(`edit/${id}`)
        $.post(`edit/${id}`, data,function(response){
            load_valor_total()
            console.log(response)
        })
    })
    load_valor_total()
</script>

trabalho6/produto/templates/produto/new.html
    <form  method="POST" style="display:flex;flex-direction:column;" id="produto-form">
            {% csrf_token %}
            {{form}}
            <input type="submit" name="Submit" style="width: 60%; margin: 0 auto;margin-top: 20px"/>
    </form>

trabalho6/produto/templates/produto/valor.html
{% load humanize %}


{{valor_final | floatformat:2|intcomma}}

trabalho6/templates/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <linkstat rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}"></linkstat>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title>{% block titulo %}Produto{% endblock %}</title>
    <style>
        {% block style %}

        {% endblock %}
    </style>
</head>
<body class="barra">

    {% block body%}

    {% endblock%}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script>
        {% block script%}
        {% endblock %}
    </script>

</body>
</html>













